#!/bin/sh


# Check linksys config for the firstboot
firstboot=$(uci get linksys.@firmware[0].eula_accepted)

if [ "$firstboot" != "1" -o -f "/etc/config/netshare" ]; then
	[[ -f /etc/config/samba ]] && echo > /etc/config/samba


cat >> /etc/config/samba << EOF
config samba
        option 'name'           'Linksys'
        option 'workgroup'      'WORKGROUP'
        option 'description'    'Samba share'
        option 'charset'        'UTF-8'
        option 'homes'          '0'

config 'sambashare'
        option 'name'           'Linksys'
        option 'path'           '/usbconf'
        option 'users'          'root'
        option 'guest_ok'       'yes'
        option 'create_mask'    '0700'
        option 'dir_mask'       '0700'
        option 'read_only'      'no'
EOF

	# Add firewall rule
	check_rule=$(uci show firewall | grep -wo 'Samba')
	if [[ -z $check_rule ]]; then
		# Add firewall rule
		uci add firewall rule
		uci set firewall.@rule[-1].name=Samba
		uci set firewall.@rule[-1].src=lan
		uci set firewall.@rule[-1].proto=tcp
		uci set firewall.@rule[-1].dest_port=139
		uci set firewall.@rule[-1].target=ACCEPT
		uci commit firewall
	fi

	# Global options
	#echo "        wide links = yes" >> /etc/samba/smb.conf.template
	sed -i "s/invalid users = root/invalid users = nobody/g" /etc/samba/smb.conf.template
	sed -i "s/guest account = nobody/guest account = root/g" /etc/samba/smb.conf.template
fi

exit 0
