#!/bin/sh

# Check linksys config for the firstboot
firstboot=$(uci get linksys.@firmware[0].eula_accepted)

if [ "$firstboot" != "1" -o -f "/etc/config/netshare" ]; then
	[[ -f /etc/vsftpd.conf ]] && echo > /etc/vsftpd.conf

cat >> /etc/vsftpd.conf << EOF
background=YES
listen=YES
anonymous_enable=YES
local_enable=NO
write_enable=YES
local_umask=022
check_shell=NO
dirmessage_enable=NO
session_support=YES
userlist_enable=NO
local_root=/usbconf
no_anon_password=YES
anon_root=/usbconf
anon_max_rate=2048000
anon_mkdir_write_enable=YES
anon_other_write_enable=YES
anon_upload_enable=YES
chroot_local_user=YES
EOF

	mkdir -p /home
	ln -s /usbconf /home/ftp
fi

exit 0
