#!/bin/sh

case "$1" in
	list)
		echo '{ "status":{}, "check":{}, "ipaddr":{}, "restart":{"interface":"str"} }'
	;;
	call)
		case "$2" in
			status)
				conn_stat="$(uci get sambuca.sambuca.wan)"
				if [ "$conn_stat" == "1" ]; then
					state="Connected"
				else
					state="Disconnected"
				fi

				printf '{ "values": { "state" : "%s" }}', $state
			;;
			check)
				$(nc -w 3 -z update1.linksys.com 443)
				[ "$(echo $?)" == "0" ] && state="Connected" || state="Disconnected"

				printf '{ "values": { "state" : "%s" }}', $state
			;;
			ipaddr)
				# local
				wan_ip="$(ifstatus wan | jsonfilter -e '@["ipv4-address"][0].address')"
				printf '{ "values": { "ipaddr" : "%s" }}', $wan_ip
			;;
			restart)
				read input
				local_interface=$(echo "$input" | jsonfilter -e '@.interface')

				# Check if interface is valid
				$(ifstatus $local_interface &> /dev/null)

				if [ "$?" == "0" ]; then
					$(ifdown $local_interface && ifup $local_interface)
				else
					local_interface="invalid"
				fi

				printf '{ "values": { "interface" : "%s" }}', $local_interface
			;;
		esac
	;;
esac
