#!/bin/sh

case "$1" in
	list)
		echo '{ "status": {"interface":"str"} }'
	;;
	call)
		case "$2" in
			status)
				read input
				interface=$(echo "$input" | jsonfilter -e '@.interface')
				iface=$(ubus call network.interface.$interface status 2>/dev/null | jsonfilter -e '@.device' 2>/dev/null)

				if [ -z "$iface" ]; then
					printf "{ \"values\": {\"status\":\"invalid\"}}"
				else
					ip=$(ifconfig $iface 2>/dev/null | grep "net addr" | awk '{print $2}' | awk -F':' '{print $2}' | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')

                                	if [ "$ip" == "" ]; then
						printf "{ \"values\": {\"status\":\"disconnected\"}}"
                                	else
						printf "{ \"values\": {\"status\":\"connected\"}}"
                                	fi
				fi
		esac
	;;
esac
